global:
    scrape_interval: 30s
    scrape_timeout: 10s
    evaluation_interval: 1m
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
    - job_name: 'cadvisor'
      scrape_interval: 1s
      static_configs:
          - targets: ['cadvisor:9000']
    - job_name: 'node-exporter'
      static_configs:
          - targets: ['node-exporter:9100']
    - job_name: 'taurus-exporter'
      scrape_interval: 1s
      static_configs:
          - targets: ['taurus:8008']