version: "2.1"
volumes:
  config_volume:
networks:
  easyminer:
services:
  easyminer-mysql:
    container_name: easyminer-mysql
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --sql_mode=""
    networks:
      - easyminer
    healthcheck:
      test: "mysql --host=easyminer-mysql --user=root --password=root  --execute='show databases' "
      interval: 15s
      retries: 5
  easyminer-frontend:
#    volumes:
#      - ./EasyMinerCenter/app:/var/www/html/easyminercenter/app
#      - config_volume:/var/www/html/easyminercenter/app/config
#      - ./EasyMinerCenter/log:/var/www/html/easyminercenter/log
    container_name: easyminer-frontend
#    travisCI
    image: wrtty/easyminer-frontend:v2.4
#    local
#    image: easyminer-frontend:v2.4-xweir00
    ports:
      - "8894:80"
    networks:
      - easyminer
    healthcheck:
      test: "curl -f http://easyminer-frontend/easyminercenter"
      interval: 30s
      retries: 5
    depends_on:
      easyminer-mysql:
        condition: service_healthy
      easyminer-scorer:
        condition: service_healthy
  easyminer-backend:
    container_name: easyminer-backend
    image: kizi/easyminer-backend:v2.4
    environment:
      - EM_USER_ENDPOINT=http://easyminer-frontend/easyminercenter
    ports:
      ["8893:8893", "8892:8892", "8891:8891"]
    networks:
      - easyminer
    healthcheck:
      test: "curl -f http://localhost:8891/easyminer-data/index.html && curl -f http://localhost:8892/easyminer-preprocessing/index.html && curl -f http://localhost:8893/easyminer-miner/index.html"
      interval: 30s
      retries: 5
    depends_on:
      easyminer-frontend:
        condition: service_healthy
  easyminer-scorer:
    container_name: easyminer-scorer
    image: kizi/easyminer-scorer:v2.4
    depends_on:
      - easyminer-mysql
    ports:
      - "8080:8080"
    networks:
      - easyminer
    healthcheck:
      test: "curl -f http://localhost:8080/swagger-ui.html"
      interval: 30s
      retries: 5
#  adminer:
#    container_name: adminer
#    image: adminer
#    ports:
#      - "8081:8080"
#    networks:
#      - easyminer
# Monitoring
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    depends_on:
      easyminer-frontend:
        condition: service_healthy
      easyminer-backend:
        condition: service_healthy
      easyminer-scorer:
        condition: service_healthy
      easyminer-mysql:
        condition: service_healthy
    command:
      - '--config.file=/etc/prometheus/confs/prometheus.yml'
    volumes:
      - ./confs/:/etc/prometheus/confs/
    ports:
      - "9090:9090"
    networks:
      - easyminer
  CAdvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    depends_on:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9000:8080"
    networks:
      - easyminer
  node-exporter:
    container_name: node-exporter
    depends_on:
      - prometheus
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - easyminer
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./data_grafana:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=kolpkolp
      # Be carefull with GF_SECURITY_ADMIN_USER (only enabled at database creation)
      - GF_SECURITY_ADMIN_USER=admin
      # To disable basic auth for Grafana
      #- GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_DOMAIN=perf.domain.test
      - GF_SERVER_ROOT_URL=https://perf.domain.test
    networks:
      - easyminer
# Testing
  taurus:
    container_name: taurus
    image: wrtty/taurus:latest
    depends_on:
      easyminer-frontend:
        condition: service_healthy
      easyminer-backend:
        condition: service_healthy
      easyminer-scorer:
        condition: service_healthy
      easyminer-mysql:
        condition: service_healthy
    ports:
      - '8008:8008'
    command:
#     TravisCI
#      - '../EasyMiner-Performance-Tests/my-config.yml'
#     Local
      - '/EasyMiner-Performance-Tests/my-config.yml'
    volumes:
      - ../EasyMiner-Performance-Tests:/EasyMiner-Performance-Tests
    networks:
      - easyminer
