version: "2.1"
volumes:
  config_volume:
networks:
  easyminer:
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/confs/prometheus.yml'
    volumes:
      - ./confs:/etc/prometheus/confs
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - easyminer
  CAdvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    depends_on:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "9000:8080"
    networks:
      - easyminer
  node-exporter:
    container_name: node-exporter
    depends_on:
      - prometheus
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - easyminer
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_BASIC_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=easyminer
# Be carefull with GF_SECURITY_ADMIN_USER (only enabled at database creation)
      - GF_SECURITY_ADMIN_USER=admin
# To disable basic auth for Grafana and enable anonymous user
#      - GF_AUTH_BASIC_ENABLED=false
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_USER_AUTO_ASSIGN_ORG_ROLE=Admin
# Not working - redirectiong to login
##      - GF_AUTH_ANONYMOUS_ORG_NAME=Kizi
##      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - easyminer
