{
 "title": "EasyMiner Docker Monitoring",
 "description": "EasyMiner Monitoring Template",
 "tags": [
  "docker",
  "node-exporter",
  "cadvisor",
  "EasyMiner",
  "prometheus"
 ],
 "time": { "from": "2019-04-09T15:13:02.255Z", "to": "2019-04-09T15:17:16.507Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_system_seconds_total, name)"
   }
  ]
 },
 "panels": [
  { "title": "Taurus test results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API avg response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "rate(bzt_test_avg_response_time_seconds_sum[5s]) \n/\nrate(bzt_test_avg_response_time_seconds_count[5s])",
     "legendFormat": "{{test_label}}"
    }
   ]
  },
  {
   "title": "Avg bytes send",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(bzt_test_send_bytes_sum[5s])\n/\nrate(bzt_test_send_bytes_count[5s])",
     "legendFormat": "{{test_label}}"
    }
   ]
  },
  {
   "title": "Concurrent users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "bzt_test_concurrent_users", "legendFormat": "{{test_label}}" }
   ]
  },
  {
   "title": "Success request current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bzt_test_success_request)" }
   ]
  },
  {
   "title": "Error request current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(bzt_test_error_request)" }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 4, "w": 19, "x": 0, "y": 18 },
     "targets": [
      { "expr": "ALERTS" }
     ]
    }
   ]
  },
  { "title": "Containers Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", name=~\"${container:pipe}\"}[1m])) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\", name=~\"${container:pipe}\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", name=~\"${container:pipe}\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", name=~\"${container:pipe}\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 36 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  }
 ]
}